repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/biomejs/pre-commit
  rev: v1.9.4
  hooks:
    - id: biome-check
    - id: biome-check
      stages: [manual]
      args: [--unsafe]